### PR TITLE
Move populate database

### PR DESCRIPTION
**Pull request by Jeronics**
- Moved the database/populate.py to populate_database.py (its a better praxis for module imports in python).
- I Added a README that will allow contributors to start right away!

### CODE REVIEW

**Comment by denisergashbaev** [comment]
I read the link you've sent me, but have not been able to find an advice regarding against putting the file in a separate module. In fact, it is advisable to separate scripts into modules according to the concerns they solve. In order to run the code from the command line, you just need to add the path to the project to the PYTHONPATH variable
```
cd PaintingTrivia
export PYTHONPATH=${PYTHONPATH}:.
python database/populate.py
```

**Comment by denisergashbaev** [comment]
You can easily revert the change by executing 
```
git revert b83871c
```
FYI, b83871c -- is the commit id where the file was renamed and moved. Afterwards just save the default git message (don't change it)

**Comment by denisergashbaev** [comment]
@Jeronics , besides comments above, the branch is broken. i cannot login

**Comment by Jeronics** [comment]
Regarding the location of the populate. The main reason I moved it is so that it can be executed through the terminal as a script. This way the setup can be automized.

**Comment by Jeronics** [comment]
Denis, delete this branch then!
I have added another pull request from the branch edit-readme.

**Pull request closed without merging**
